name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image up to dev stage
      run: docker build --target dev -t app:dev -f app/Dockerfile app

    - name: Run tests inside Docker
      run: docker run --rm app:dev npm run test:prod

    - name: Build and push final Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: |
          ghcr.io/cykl_zycia_i_narzedzia_devops:latest
          ghcr.io/cykl_zycia_i_narzedzia_devops:${{ github.sha }} 