name: Build and Test on PR

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t app:test -f app/Dockerfile .

    - name: Run tests inside Docker
      run: docker run --rm app:test npm test